// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDUAFVthKzzTSn9H48f5RdVKikSmqDGLQ',
    appId: '1:1024608459621:web:8ab721a1d8f796bbfbdf8c',
    messagingSenderId: '1024608459621',
    projectId: 'projeto-spd',
    authDomain: 'projeto-spd.firebaseapp.com',
    storageBucket: 'projeto-spd.appspot.com',
    measurementId: 'G-HR5QXV879E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrebo-qd6C7AP9wrNZtorDMde0q3hOpnM',
    appId: '1:1024608459621:android:a6fecc3b0b557166fbdf8c',
    messagingSenderId: '1024608459621',
    projectId: 'projeto-spd',
    storageBucket: 'projeto-spd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuPaHlqE58IS5RIGfzfAeeHB9MAK41VKE',
    appId: '1:1024608459621:ios:eee5d2f4ff434b09fbdf8c',
    messagingSenderId: '1024608459621',
    projectId: 'projeto-spd',
    storageBucket: 'projeto-spd.appspot.com',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuPaHlqE58IS5RIGfzfAeeHB9MAK41VKE',
    appId: '1:1024608459621:ios:2c2dda5e5d0df5acfbdf8c',
    messagingSenderId: '1024608459621',
    projectId: 'projeto-spd',
    storageBucket: 'projeto-spd.appspot.com',
    iosBundleId: 'com.example.flutterMaps.RunnerTests',
  );
}
